---
cluster_name: test
cluster_hostname: test-cluster.aws
cluster_ip_address: 10.0.0.1
node_machine_type_identifier: m5-12xlarge
total_nodes_count: 5
active_data_nodes: 4
master_eligible_nodes_count: 1
index_count: 100
#shards_per_index: 5 
primary_shards_per_index: 5
replica_shards_per_index: 5
#total_shards_per_index: primary_shards_per_index * (1 + replica_shards_per_index)
index_roll_over_size_gb: 50
index_clean_up_age_days: 20
#node_disk_volume_gb: 100 # discuss effect of node addition/removal
total_disk_size_gb: 2000
simulation_frequency_minutes: 5

# Specify data ingestion with respect to time of the day to represent pattern for entire day(24hrs).
states:
- position: 1
  time_hh_mm_ss: '00_00_00'
  ingestion_rate_gb_per_hr: 10
  searches:
    simple: 35
    medium: 10
- position: 2
  time_hh_mm_ss: '06_00_00'
  ingestion_rate_gb_per_hr: 60
  searches:
    simple: 80
    medium: 70
    complex: 10
- position: 3
  time_hh_mm_ss: '12_00_00'
  ingestion_rate_gb_per_hr: 65
  searches:
    simple: 400
    medium: 350
    complex: 160
- position: 4
  time_hh_mm_ss: '18_00_00'
  ingestion_rate_gb_per_hr: 15
  searches:
    simple: 200
    medium: 150
    complex: 80
- position: 5
  time_hh_mm_ss: '23_00_00'
  ingestion_rate_gb_per_hr: 5
  searches:
    simple: 40
    medium: 30
randomness_percentage: 5


# Specify searches along with their type, probability and load inflected on the cluster.
search_description:
  simple:
    cpu_load_percent: 1
    memory_load_percent: 2
    heap_load_percent: 2
  medium:
    cpu_load_percent: 2
    memory_load_percent: 3
    heap_load_percent: 3
  complex:
    cpu_load_percent: 5
    memory_load_percent: 6
    heap_load_percent: 6
